export default {
  UPDATE_CONTRACTS_LIST: 'CONTRACTS_UPDATE_CONTRACTS_LIST',
  UPDATE_PAGINATION: 'CONTRACTS_UPDATE_PAGINATION',
  UPDATE_PAGINATION_PAGE: 'CONTRACTS_UPDATE_PAGINATION_PAGE',
  UPDATE_CONTRACT: 'CONTRACTS_UPDATE_CONTRACT',
  ADD_SELLER_COMPANY: 'CONTRACTS_ADD_SELLER_COMPANY',
  ADD_CLIENT_COMPANIES: 'CONTRACTS_ADD_CLIENT_COMPANIES',
};
