export default {
  UPDATE_CONTRACTS_LIST: 'CONTRACTS_UPDATE_CONTRACTS_LIST',
  UPDATE_PAGINATION: 'CONTRACTS_UPDATE_PAGINATION',
  UPDATE_PAGINATION_PAGE: 'CONTRACTS_UPDATE_PAGINATION_PAGE',
  UPDATE_CONTRACT: 'CONTRACTS_UPDATE_CONTRACT',
};
