export default {
  UPDATE_COMPANIES_LIST: 'COMPANIES_UPDATE_COMPANIES_LIST',
  UPDATE_PAGINATION: 'COMPANIES_UPDATE_PAGINATION',
  UPDATE_PAGINATION_PAGE: 'COMPANIES_UPDATE_PAGINATION_PAGE',
  SELECT_COMPANY: 'COMPANIES_SELECT_COMPANY',
};
